In [1]:
import numpy as np # as로 변수를 기호에 맞게 쓰면 된다
test_array = np.array([1, 4, 5, 8], float) # 숫자의 형태를 정해줄 수 있다
print(test_array) # 배열 전체 출력
print(test_array[2]) # 2번 인덱스 원소 출력
print(type(test_array[3])) # 데이터타입 보기

[1. 4. 5. 8.]
5.0
<class 'numpy.float64'>


In [2]:
import numpy as np
test_list = [[1, 4, 5, 8], [1, 4, 5, 9]] # 파이썬의 리스트
np.array(test_list, float) # 넘파이 배열 변환

array([[1., 4., 5., 8.],
       [1., 4., 5., 9.]])

In [3]:
print(test_array.dtype) # 배열 전체의 데이터 타입 반환
print(test_array.shape) # 배열의 구조(shape)를 반환함

float64
(4,)


In [4]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape # 배열의 구조를 봄

(3, 4)

In [5]:
tensor_rank3 = [
[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
np.array(tensor_rank3, int).shape # 3차원 배열(텐서)의 구조

(4, 3, 4)

In [6]:
tensor_rank3 = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], 
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
np.array(tensor_rank3, int).ndim # 차원 수 출력

3

In [7]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)
# 매개변수 dtype으로 넘파이 배열의 데이터 타입 지정
# dtype을 실수형인 float으로 지정한다면 모든 데이터가
# 실수형으로 저장되는 것을 확인 가능

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
import sys
np.array( [[1, 2, 3.5], [4, 5, 6.5]],
dtype=np.float64).itemsize
# itemsize =  각 요소가 차지하는 바이트의 수

8

In [9]:
 np.array( [[1, 2, 3.5], [4, 5, 6.5]], 
dtype=np.float32).itemsize

4

In [10]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [11]:
x = x.reshape(-1,)
x
# reshape: 배열의 구조를 변경하고 랭크를 조절

array([1, 2, 5, 8, 1, 2, 5, 8])

In [12]:
x.shape

(8,)

In [13]:
x.reshape(4,2) # 4행 2열로 구조변환

array([[1, 2],
       [5, 8],
       [1, 2],
       [5, 8]])

In [14]:
y= np.array(range(8)).reshape(4,2)
y
# range(8): 0~7까지 배열생성
# resape(4,2): 4행 2열로 생성

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
y.reshape(2,-1)
# -1을 사용하면 나머지 차원의 크기를 지정했을 때
# 전체 요소의개수를 고려하여 마지막 차원이 자동으로 지정됨

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
y.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
x.flatten()
# flatten: 데이터 그대로 1차원으로 변경

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
x = np.array([[1, 2, 3], [4, 5, 6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
x[0][0] # 인덱스의 값 호출

1

In [21]:
x[0, 1] = 100
x # 100 대입 후 출력

array([[  1, 100,   3],
       [  4,   5,   6]])

In [22]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x[:,2:] # 전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [23]:
x[1,1:3] # 1행의 1열 ~ 2열

array([7, 8])

In [24]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [25]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
x[:,::2] # 콜른 두개 + 건너뛰는 칸수

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [27]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [28]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
x[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
np.arange(-5, 5) # 배열 만드는 범위

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [31]:
np.arange(0, 5, 0.5) # 0부터 5까지 0,5씩 증가한다

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [32]:
np.ones(shape=(5,2), dtype=np.int8) # ones = 숫자 1로만 배열을 구성한다

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [33]:
np.zeros(shape=(2,2), dtype=np.float32) # zeros = 숫자 0으로만 배열을 구성한다

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [34]:
np.empty(shape=(2,4), dtype=np.float32) # 배열안에 랜덤의 쓰레기 값을 넣는다

array([[5.7857652e-39, 8.4489539e-39, 5.3265527e-39, 7.8061461e-39],
       [9.2755463e-39, 1.0561242e-38, 0.0000000e+00, 4.5910742e-41]],
      dtype=float32)

In [35]:
np.identity(n=3, dtype=int) # n x n의 단위 행렬을 n크기만큼 생성한다

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
np.eye(N=3, M=5) # N은 행의 개수, M은 열의 개수를 지정해준다

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [37]:
np.eye(N=3, M=5, k=2) # k는 시작할 인덱스 위치를 지정해준다

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
np.diag(matrix) # 대각선의 값을 출력해준다

array([0, 4, 8])

In [40]:
np.diag(matrix, k=1) # k로 옮기기 가능

array([1, 5])

In [41]:
np.random.uniform(0, 5, 10) # (시작값, 끝값, 데이터개수)를 랜덤으로 출력해준다

array([1.54012023, 1.27092571, 1.50695211, 3.63761496, 1.34810017,
       0.2161758 , 0.64602719, 1.62855469, 3.93813895, 1.88411652])

In [42]:
np.random.normal(0, 2, 10) # (평균값, 분산, 데이터개수)를 랜덤으로 출력해준다

array([ 0.46303312,  2.99381046,  0.21385466, -0.70751302,  5.1249191 ,
       -1.02731089, -0.26779767,  0.22180189,  1.40658955,  3.07049409])

In [43]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
test_array.sum(axis=0) # axis = 0 은 행끼리의 연산

array([15, 18, 21, 24])

In [45]:
test_array.sum(axis=1) # axis = 1 은 열끼리의 연산

array([10, 26, 42])

In [46]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
test_array.mean(axis=1) # axis=1 축을 기준으로 평균 연산

array([ 2.5,  6.5, 10.5])

In [48]:
test_array.std() # 전체 값에 대한 표준편차 연산

3.452052529534663

In [49]:
np.sqrt(test_array) # 각 요소에 제곱근 연산 수행

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [50]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2)) #vstack 함수 : 배열을 수직으로 붙여 하나의 행렬을 생성

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.hstack((v1,v2)) #hstack 함수 : 배열을 수평으로 붙여 하나의 행렬을 생성

array([1, 2, 3, 4, 5, 6])

In [52]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
print(x + 10) # 브로드캐스팅 연산 각 배열 칸마다 계산이 가능하다
print(x - 2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [54]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
print(x + x)
print(x - x)
print(x / x)
print(x * x)
print(x ** x) # 세제곱 연산

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 1  4  9]
 [16 25 36]]
[[    1     4    27]
 [  256  3125 46656]]


In [56]:
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
print(x_1)
print(x_2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [57]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [58]:
x = np.arange(1, 10).reshape(3,3)
print(x)
print(x+10)
print(x-2)
print(x // 3)
print(x ** 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[0 0 1]
 [1 1 2]
 [2 2 3]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [59]:
x = np.arange(1, 16).reshape(3,5)
print(x / 3) # 나눗셈 소수점 출력
print(x // 3) # 소수점 뒷자리 삭제

[[0.33333333 0.66666667 1.         1.33333333 1.66666667]
 [2.         2.33333333 2.66666667 3.         3.33333333]
 [3.66666667 4.         4.33333333 4.66666667 5.        ]]
[[0 0 1 1 1]
 [2 2 2 3 3]
 [3 4 4 4 5]]


In [60]:
x = np.array([4, 6, 7, 3, 2])
print((x > 3))
print((x > 3).all()) # and 연산자
print((x > 3).any()) # or 연산자

[ True  True  True False False]
False
True


In [61]:
 x = np.array([4, 6, 7, 3, 2])
print(x > 5)
print(np.where(x>5))

[False  True  True False False]
(array([1, 2], dtype=int64),)


In [62]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5 , 10, 20) # (비교연산자, 참일때 대입, 거짓일때 대입)

array([20, 10, 10, 20, 20])

In [63]:
x = np.array([4, 6, 7, 3, 2]) # 배열내 작은 값 순서대로 반환
print(np.argsort(x)) # index 값
print(x[np.argsort(x)]) # 배열 안 숫자 값
print(np.argmax(x)) # 가장 큰 값
print(np.argmin(x)) # 가장 작은 값

[4 3 0 1 2]
[2 3 4 6 7]
2
4


In [64]:
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [65]:
cond = x > 3
x[cond] # 조건에 해당하는 값만 출력

array([4, 6, 7])

In [66]:
x = np.array([4, 6, 7, 3, 2]) # 팬시 인덱스
cond = np.array([1, 2, 0, 3, 4, 2,], int) # 각 n번에 있는 인덱스 불러오기
x[cond]

array([6, 7, 4, 3, 2, 7])